---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'RStudio Team Standalone'

Parameters:
  useVPC:
    Type: AWS::EC2::VPC::Id
    Description: "VPC to deploy the cluster into."
  useSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: "Subnet to deploy the cluster into. Must be in the selected VPC."
  cidrIpHTTP:
    Type: String
    Description: "Security groups CIDR range for ports 80 and 443."
    Default: "0.0.0.0/0"
  cidrIpSSH:
    Type: String
    Description: "Security groups CIDR range for port 22."
    Default: "0.0.0.0/0"
  keyName:
    Type: AWS::EC2::KeyPair::KeyName
    AllowedPattern: ".+"
    ConstraintDescription: Must select an existing EC2 KeyPair
    Description: "AWS key pair to use to SSH to the VMs. SSH username for the VMs are ubuntu (has sudo privilege). SSH into machines for changing configuration, reviewing logs, etc."
  rspInstanceType:
    Type: String
    Default: m5.large
    AllowedValues:
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - r5.12xlarge
      - r5.16xlarge
      - r5.24xlarge
    Description: EC2 Instance type for RStudio Server Pro. Default is m5.large.
  rspDiskSize:
    Type: Number
    Default: 50
    MinValue: 50
    Description: Volume size for RStudio Server Pro EC2 Instance. Min 50 GB.
  rscInstanceType:
    Type: String
    Default: m5.large
    AllowedValues:
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - r5.12xlarge
      - r5.16xlarge
      - r5.24xlarge
    Description: EC2 Instance type for RStudio Connect. Default is m5.large.
  rscDiskSize:
    Type: Number
    Default: 50
    MinValue: 50
    Description: Volume size for RStudio Connect EC2 Instance. Min 50 GB.
  rspmInstanceType:
    Type: String
    Default: m5.large
    AllowedValues:
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - r5.12xlarge
      - r5.16xlarge
      - r5.24xlarge
    Description: EC2 Instance type for RStudio Package Manager. Default is m5.large.
  rspmDiskSize:
    Type: Number
    Default: 120
    MinValue: 120
    Description: Volume size for RStudio Package Manager EC2 Instance. Min 120 GB.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Global Network configuration
        Parameters:
          - useVPC
          - useSubnet
          - cidrIpHTTP
          - cidrIpSSH
      -
        Label:
          default: Global EC2 resource configuration
        Parameters:
          - keyName
      -
        Label:
          default: RStudio Server Pro EC2 resource configuration
        Parameters:
          - rspInstanceType
          - rspDiskSize
      -
        Label:
          default: RStudio Connect EC2 resource configuration
        Parameters:
          - rscInstanceType
          - rscDiskSize
      -
        Label:
          default: RStudio Package Manager EC2 resource configuration
        Parameters:
          - rspmInstanceType
          - rspmDiskSize
    ParameterLabels:
      useSubnet:
        default: "Deploy to Subnet"
      useVPC:
        default: "Deploy to VPC"
      cidrIpHTTP:
        default: "Security group CIDR Range for HTTP/HTTPS"
      cidrIpSSH:
        default: "Security group CIDR Range for SSH"
      useVPC:
        default: "Deploy to VPC"
      keyName:
        default : "AWS keypair"
      rspInstanceType:
        default : "RStudio Server Pro Instance Type"
      rspDiskSize:
        default : "RStudio Server Pro Disk Size"
      rscInstanceType:
        default : "RStudio Connect Instance Type"
      rscDiskSize:
        default : "RStudio Connect Disk Size"
      rspmInstanceType:
        default : "RStudio Package Manager Instance Type"
      rspmDiskSize:
        default : "RStudio Package Manager Disk Size"

Mappings:
  RSPRegionMap:
    ap-northeast-1:
      AMI: ami-089dbb2aafe4507ad
    ap-northeast-2:
      AMI: ami-0281606354e8e6768
    ap-south-1:
      AMI: ami-0c1a7524f33545ce5
    ap-southeast-1:
      AMI: ami-0bf8a29c62d5156e8
    ap-southeast-2:
      AMI: ami-06b0fade7edc313ad
    eu-central-1:
      AMI: ami-0e284982aeeadfa8e
    eu-north-1:
      AMI: ami-0ba34fa2cb4e369b9
    eu-west-1:
      AMI: ami-010bd93e570070ca0
    eu-west-2:
      AMI: ami-02332278c2064b57c
    eu-west-3:
      AMI: ami-0790eaebd8188279e
    us-east-1:
      AMI: ami-0893c8bcf961b37fc
    us-east-2:
      AMI: ami-0a0fcfe7249fac9f5
    us-west-1:
      AMI: ami-0d604623cad21cbac
    us-west-2:
      AMI: ami-0afb3900b3e6fd59a

  RSCRegionMap:
    eu-central-1:
      AMI: ami-094b7f5cae87907dd
    eu-north-1:
      AMI: ami-0ea31068e99f8df91
    eu-west-1:
      AMI: ami-0e958dba717422144
    eu-west-2:
      AMI: ami-0e0633ab0869ee960
    eu-west-3:
      AMI: ami-0355e9150a06de678
    us-east-1:
      AMI: ami-01b2d1ebce4dba914
    us-east-2:
      AMI: ami-09103663a28d3b6ce
    us-west-1:
      AMI: ami-04ed4e5e4ce91002c
    us-west-2:
      AMI: ami-05aa2331ff635008d
    ap-northeast-1:
      AMI: ami-0c72a69fd8f76bfbf
    ap-northeast-2:
      AMI: ami-04912a71571a0e3fd
    ap-south-1:
      AMI: ami-0b0e0f8a466687432
    ap-southeast-1:
      AMI: ami-0eb2e999f192e0f3f
    ap-southeast-2:
      AMI: ami-08f4772373c299cea

  RSPMRegionMap:
    eu-central-1:
      AMI: ami-01aa8c68198f50949
    eu-north-1:
      AMI: ami-0f91b8833026dc677
    eu-west-1:
      AMI: ami-0a35783d62a694f07
    eu-west-2:
      AMI: ami-04f3891b57f72d156
    eu-west-3:
      AMI: ami-07f15e5d10f19f45c
    us-east-1:
      AMI: ami-0b67497386d94876f
    us-east-2:
      AMI: ami-077706d681ccd250b
    us-west-1:
      AMI: ami-0ea37668564fd9ada
    us-west-2:
      AMI: ami-0dc8151e53de2a56f
    ap-northeast-1:
      AMI: ami-01b24d36b8500b4a4
    ap-northeast-2:
      AMI: ami-008bd0a5a27463e9d
    ap-south-1:
      AMI: ami-0a3d254c2a454ebc8
    ap-southeast-1:
      AMI: ami-0c184ad733fa9eb42
    ap-southeast-2:
      AMI: ami-0d9fdec2761824f47

Resources:
  RSPInstance:
    Type: AWS::EC2::Instance
    DependsOn:
      - RSCInstance
      - RSPMInstance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    Properties:
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref "AWS::StackName", "RStudioServerPro"]]
      ImageId: !FindInMap [RSPRegionMap, !Ref "AWS::Region", AMI]
      KeyName: !Ref keyName
      InstanceType: !Ref rspInstanceType
      NetworkInterfaces:
        - DeleteOnTermination: "true"
          AssociatePublicIpAddress: "true"
          DeviceIndex: 0
          SubnetId: !Ref useSubnet
          GroupSet: [!Ref RSPSecurityGroup]
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref rscDiskSize
            DeleteOnTermination: true
            VolumeType: gp2
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash -xe
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            trap '/usr/local/bin/cfn-signal --exit-code 1 --resource RSPInstance --region ${AWS::Region} --stack ${AWS::StackName}' ERR

            RSESSION_CONFIG_FILE=/etc/rstudio/rsession.conf
            sed -i -e "s|#default-rsconnect-server=RSC_SERVER_ADDRESS|default-rsconnect-server=http://${RSC_IP}|" $RSESSION_CONFIG_FILE

            REPOS_CONFIG_FILE=/etc/rstudio/repos.conf
            sed -i -e "s|#CRAN=RSPM_SERVER_ADDRESS|CRAN=http://${RSPM_IP}/cran/__linux__/bionic/latest|" $REPOS_CONFIG_FILE

            # Start Sessions
            /opt/R/3.6.3/bin/R --version
            /opt/R/3.6.3/bin/R --no-save -e "library(dplyr)"
            /opt/python/3.8.1/bin/python --version
            /opt/python/3.8.1/bin/python -c "import pandas"

            # Verify
            systemctl enable rstudio-server
            systemctl enable rstudio-launcher
            systemctl start rstudio-server
            systemctl start rstudio-launcher

            /usr/local/bin/wait-for-it.sh localhost:80 -t 60
            rstudio-server stop
            sleep 10
            rstudio-server verify-installation --verify-user rstudio-user || true
            sleep 10
            rstudio-server start

            /usr/local/bin/wait-for-it.sh localhost:80 -t 60
            /usr/local/bin/cfn-signal --exit-code 0 --resource RSPInstance --region ${AWS::Region} --stack ${AWS::StackName}

          - RSC_IP: !GetAtt RSCInstance.PublicIp
            RSPM_IP: !GetAtt RSPMInstance.PublicIp

  RSPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RStudio Server Pro Access
      VpcId: !Ref useVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref cidrIpSSH
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: !Ref cidrIpHTTP
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: !Ref cidrIpHTTP

  RSPSecurityGroupSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RSPSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref RSPSecurityGroup

  RSCInstance:
    Type: AWS::EC2::Instance
    DependsOn:
      - RSPMInstance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    Properties:
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref "AWS::StackName", "RStudioConnect"]]
      ImageId: !FindInMap [RSCRegionMap, !Ref "AWS::Region", AMI]
      KeyName: !Ref keyName
      InstanceType: !Ref rscInstanceType
      NetworkInterfaces:
        - DeleteOnTermination: "true"
          AssociatePublicIpAddress: "true"
          DeviceIndex: 0
          SubnetId: !Ref useSubnet
          GroupSet: [!Ref RSCSecurityGroup]
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref rscDiskSize
            DeleteOnTermination: true
            VolumeType: gp2
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash -xe
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            trap '/usr/local/bin/cfn-signal --exit-code 1 --resource RSCInstance --region ${AWS::Region} --stack ${AWS::StackName}' ERR

            /usr/local/bin/wait-for-it.sh localhost:80 -t 60
            sleep 5  # Wait for admin user creation
            systemctl stop rstudio-connect

            CONNECT_CONFIG_FILE=/etc/rstudio-connect/rstudio-connect.gcfg
            sed -i -e 's|;\[RPackageRepository "CRAN"\]|\[RPackageRepository "CRAN"\]|' $CONNECT_CONFIG_FILE
            sed -i -e 's|;\[RPackageRepository "RSPM"\]|\[RPackageRepository "RSPM"\]|' $CONNECT_CONFIG_FILE
            sed -i -e "s|;URL = RSPM_SERVER_ADDRESS|URL = http://${RSPM_IP}/cran/__linux__/bionic/latest|" $CONNECT_CONFIG_FILE

            systemctl start rstudio-connect

            /usr/local/bin/wait-for-it.sh localhost:80 -t 60
            /usr/local/bin/cfn-signal --exit-code 0 --resource RSCInstance --region ${AWS::Region} --stack ${AWS::StackName}

          - RSPM_IP: !GetAtt RSPMInstance.PublicIp

  RSCSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RStudio Connect Access
      VpcId: !Ref useVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref cidrIpSSH
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: !Ref cidrIpHTTP
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: !Ref cidrIpHTTP

  RSCSecurityGroupSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RSCSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref RSCSecurityGroup

  RSPMInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT20M
    Properties:
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref "AWS::StackName", "RStudioPM"]]
      ImageId: !FindInMap [RSPMRegionMap, !Ref "AWS::Region", AMI]
      KeyName: !Ref keyName
      InstanceType: !Ref rspmInstanceType
      NetworkInterfaces:
        - DeleteOnTermination: "true"
          AssociatePublicIpAddress: "true"
          DeviceIndex: 0
          SubnetId: !Ref useSubnet
          GroupSet: [!Ref RSPMSecurityGroup]
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref rspmDiskSize
            DeleteOnTermination: true
            VolumeType: gp2
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash -xe
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            trap '/usr/local/bin/cfn-signal --exit-code 1 --resource RSPMInstance --region ${AWS::Region} --stack ${AWS::StackName}' ERR

            /usr/local/bin/wait-for-it.sh localhost:80 -t 60
            /usr/local/bin/cfn-signal --exit-code 0 --resource RSPMInstance --region ${AWS::Region} --stack ${AWS::StackName}

  RSPMSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RStudio Package Manager Access
      VpcId: !Ref useVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref cidrIpSSH
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: !Ref cidrIpHTTP
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: !Ref cidrIpHTTP

  RSPMSecurityGroupSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RSPMSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref RSPMSecurityGroup

Outputs:
  RSPHost:
    Description: RStudio Server Pro UI
    Value: !Join [ "", ["http://", !GetAtt RSPInstance.PublicIp]]
  RSPDefaultUser:
    Description: RStudio Server Pro default user
    Value: rstudio-user
  RSPDefaultPassword:
    Description: RStudio Server Pro initial default user password
    Value: !Ref RSPInstance
  RSCHost:
    Description: RStudio Connect UI
    Value: !Join [ "", ["http://", !GetAtt RSCInstance.PublicIp]]
  RSCDefaultUser:
    Description: RStudio Connect default user
    Value: admin
  RSCDefaultPassword:
    Description: RStudio Connect initial default user password
    Value: !Ref RSCInstance
  RSPMHost:
    Description: RStudio Package Manager UI
    Value: !Join [ "", ["http://", !GetAtt RSPMInstance.PublicIp]]
